action_id: trunk-single-player-auto-on-upgrade
date: 2024-05-21 16:11:09
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1716307869
full_timestamp:
  nanos: 515312000
  seconds: 1716307869
trunk_version: 1.22.0
