action_id: trunk-cache-prune
date: 2024-05-21 16:11:09
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1716307869
full_timestamp:
  nanos: 593000000
  seconds: 1716307869
trunk_version: 1.22.0
