action_id: trunk-share-with-everyone
date: 2024-06-18 04:57:35
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1718686655
full_timestamp:
  nanos: 799406000
  seconds: 1718686655
trunk_version: 1.22.0
